" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.
" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
"
"Added this block below to load vim-plug to get plugins to Vim, I have no idea
"what I'm doing and it's 3:24am, so take that as you will. I was follwing
"documentation from https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation  -Conner
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/bundle')
"Loading vim-plug itself
Plug 'junegunn/vim-plug'

"fzf
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

"lightline
Plug 'itchyny/lightline.vim'

"Multiple Cursors
Plug 'terryma/vim-multiple-cursors'

"vim-surround [Surrounds text with matching {}/()]
Plug 'tpope/vim-surround'

"nerdtree tree viewer
Plug 'scrooloose/nerdtree'

"GitGutter
Plug 'airblade/vim-gitgutter'

call plug#end()

"Command to automatically start NerdTree
autocmd vimenter * NERDTree
